syntax enable
colorscheme solarized
let mapleader = ";"

if has('gui_running')
    set background=light
else
    set background=dark
endif


" don't lose selection when changing indent
"
xnoremap <  <gv
xnoremap >  >gv

call plug#begin()
Plug 'xolox/vim-misc'
Plug 'xolox/vim-easytags'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'terryma/vim-multiple-cursors'
Plug 'dyng/ctrlsf.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'Raimondi/delimitMate'
Plug 'Valloric/YouCompleteMe'
Plug 'tpope/vim-commentary'
Plug 'airblade/vim-gitgutter'
Plug 'peterhoeg/vim-qml'
Plug 'easymotion/vim-easymotion'
Plug 'rhysd/vim-clang-format'
Plug '907th/vim-auto-save'
Plug 'mhinz/vim-startify'
Plug 'majutsushi/tagbar'
Plug 'wellle/targets.vim'
Plug 'floobits/floobits-neovim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

" airline
let g:airline_theme='solarized'
let g:airline_solarized_bg='dark'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

nnoremap <C-f> :CtrlSF<CR>
vnoremap <silent> <C-f> :<BS><BS><BS><BS><BS>CtrlSF <C-R>*<CR>
let g:ctrlsf_default_root='project'
let g:ctrlsf_ackprg = 'rg'
set laststatus=2

nmap F <Plug>(easymotion-overwin-f2)
map  / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)

" highlight word under cursor without jumping
nnoremap # #*

" close quickfix window
nnoremap <leader>q :cclose<CR>

" edit config
nnoremap <leader>ce :e $MYVIMRC<CR>
" reload config
nnoremap <leader>cr :so $MYVIMRC<CR>

" buffers
"   navigation
noremap <C-e> :bn<CR>
noremap <C-q> :bN<CR>

" fzf
noremap ' :Buffers<CR>
nnoremap <silent> t :GFiles<CR>
noremap <leader>n :Files<CR>
noremap <leader>v :Tags<CR>

" c++
nnoremap <silent> <leader>d :YcmCompleter GoTo<CR>
nnoremap <silent> <leader>g :YcmCompleter FixIt<CR>
let g:clang_format#detect_style_file = 1
let g:clang_format#auto_format_on_insert_leave = 1
let g:easytags_async = 1
let g:easytags_syntax_keyword = 'always'
nnoremap <silent> <leader>f :ClangFormat<CR>
vnoremap <silent> <leader>f :ClangFormat<CR>

set hidden
" Complete opts
set completeopt=menuone,menu,longest
set completeopt-=preview
set showcmd            " display incomplete commands

set hidden             " allow unsafed buffers
set nobackup           " keep a backup file (restore to previous version)
set undofile           " keep an undo file (undo changes after closing)
set ruler              " show the cursor position all the time
set tw=80
set colorcolumn=+1     " show a ruler after column 80
set t_Co=256
set scrolloff=3        " keep n lines above/below the cursor

set number
set nowrap
set showmode
set ignorecase
set smartcase
set smarttab
set smartindent
set autoindent
set softtabstop=4
set shiftwidth=4
set expandtab
set incsearch
set cmdheight=1
set showmatch                   " highlight matching [{()}]
set incsearch                   " search as characters are entered
set hlsearch                    " highlight matches
set lazyredraw                  " don't update screen inside macros, etc
set matchtime=2                 " ms to show the matching paren for showmatch
set number                      " line numbers
set ruler                       " show the cursor position all the time
set showcmd                     " display incomplete commands
set showmatch                   " show matching brackets while typing
set display=lastline,uhex       " show last line even if too long; use <xx>
set linebreak                   " break on what looks like boundaries
set showbreak=↳\                " shown at the start of a wrapped line
"set textwidth=80                " wrap after 80 columns
set virtualedit=block           " allow moving visual block into the void
" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>
" move vertically by visual line
nnoremap j gj
nnoremap k gk
inoremap jj <esc>
filetype plugin indent on

set tags=./tags;

set listchars=tab:↹·,extends:⇉,precedes:⇇,nbsp:␠,trail:␠,nbsp:␣
set wildignore+=*/tmp/*,*/build/*,*.swp,*.swo,*.zip,.git,.cabal-sandbox

autocmd BufWritePre * %s/\s\+$//e   " Removes trailing spaces
let g:auto_save = 0  " enable AutoSave on Vim startup
