actions:
  pre:
    vim-plug-install: test -e ~/.local/share/nvim/site/autoload/plug.vim || ( curl
      -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim)
  vim-plug: nvim +PlugInstall +qall
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_by_default: true
  longkey: true
  workdir: ~/.config/dotdrop
dotfiles:
  f__config_i3_config:
    dst: ~/.config/i3/config
    link: true
    src: config/i3/config
  f_config_nvim_coc-settings.json:
    dst: ~/.config/nvim/coc-settings.json
    link: true
    src: config/nvim/coc-settings.json
  f_config_nvim_init.vim:
    actions:
    - vim-plug-install
    - vim-plug
    dst: ~/.config/nvim/init.vim
    link: true
    src: config/nvim/init.vim
  f_config_nvim_settings.json:
    dst: ~/.config/nvim/settings.json
    link: true
    src: config/nvim/settings.json
  f_gitconfig:
    dst: ~/.gitconfig
    link: true
    src: gitconfig
  f_zshrc:
    dst: ~/.zshrc
    link: true
    src: zshrc
profiles:
  HoG:
    dotfiles:
    - f_gitconfig
    - f_config_nvim_init.vim
    - f_zshrc
    - f_config_nvim_settings.json
    - f_config_nvim_coc-settings.json
    - f__config_i3_config
  zadash:
    dotfiles:
    - ALL
